### ISSUE TITLE
aot issue

### ISSUE THREAD

**Issue by ghost** [juristr/video-your-first-ng2-app#3]
![image](https://user-images.githubusercontent.com/1841956/29261338-9ce94100-80ec-11e7-84ce-4b10aa15a778.png)

I am getting this error while running npm run build.prod

**Comment by juristr** [comment]
Hey, I'm not currently in front of any computer. Will check later and let you know.

**Comment by eldelosgatoss** [comment]
i have same error.

**Comment by juristr** [comment]
@jariwbh @JohanWorm Hey guys, can you provide me some more details. I just pulled the latest version from this repo and run it executing `npm run build.prod`. It seems to work on my MacOS

![image](https://user-images.githubusercontent.com/542458/29428835-e8df5f5a-838e-11e7-9dc8-d0abc5706322.png)

Can you let me know like which Angular CLI version ur using? And also on which operating system?

**Comment by juristr** [comment]
Oh...now I think I was able to repo it... 🤔. Removed my existing `node_modules` and reinstalled them and got the error

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/juri/coding/firstngapp/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts
```

I'll let u know

**Comment by juristr** [comment]
@jariwbh @JohanWorm Ok guys, think I resolved it. This commit should do it: https://github.com/juristr/video-your-first-ng2-app/commit/bcdefa65e155ad568c8705a71414652ddfee69c7

It seems as if this was an Angular CLI issue. Please get the latest code from this repo and make sure to re-install your `node_modules`. That should resolve the issue.

Sorry for the inconvenience and feel free to reopen the issue if the problem persists. Have good day 👍
